# Basic Information
title: Srinath Srinivasan
position: Master's student
affiliation: North Carolina State University
email: ssrini27 (at) ncsu.edu

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Srinath Srinivasan, Srinath, Srinath NCSU, NCSU ML, NCSU AI, NCSU HPC, tensor
description: Srinath Srinivasan homepage
canonical: https://srina1h.github.io

# Links
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=NSIyfpAAAAAJ&hl=en
cv_link: assets/files/cv.pdf
github_link: https://github.com/srina1h
linkedin: https://www.linkedin.com/in/srina1h
# twitter: https://twitter.com/

# Images (e.g., your profile picture and your website's favicon)
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively.
avatar: ./assets/img/avatar.jpg
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: true

# Google Analytics ID
# Please remove this if you don't use Google Analytics
google_analytics: G-XZCVSHDE07

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
